### ISSUE TITLE
It will start then it will stop

### ISSUE THREAD

**Issue by ezekel** [coreybutler/node-windows#128]
@coreybutler ,

Hi can you help me please, I started the service but when it start after few seconds 6-10 secs. it will stop this is the error log in daemon.

```
C:\wamp\www\mysite\node_modules\node-env-file\lib\index.js:130
            throw new TypeError("Environment file doesn't exist: " + env_file)
            ^

TypeError: Environment file doesn't exist: C:\.env
    at module.exports (C:\wamp\www\mysite\node_modules\node-env-file\lib\index.js:130:19)
    at Object.<anonymous> (C:\wamp\www\mysite\public\js\netsocket.js:17:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

```

Thank you in advance

**Comment by ezekel** [comment]
I fixed it now thank you
