### ISSUE TITLE
Missing comma in lib/Wrapper.js

### ISSUE THREAD

**Issue by manuRichard** [coreybutler/node-windows#271]
There is a missing comma in wrapper.js, in line 69:
`   child = null
    `
I think is breaking things in my environment, is that possible?

**Comment by jmparody** [comment]
Follow up on manuRichard's comment.
This is the log of the error we see when deploying our system:
`C:\MY_DIR\node_modules\node-windows\lib\wrapper.js:177
    child.send('shutdown');
          ^

TypeError: Cannot read property 'send' of null
    at process.killkid (C:\MY_DIR\node_modules\node-windows\lib\wrapper.js:177:11)
    at process.emit (events.js:321:20)
    at process.exit (internal/process/per_thread.js:165:15)
    at monitor (C:\MY_DIR\node_modules\node-windows\lib\wrapper.js:99:17)
    at ChildProcess.<anonymous> (C:\MY_DIR\node_modules\node-windows\lib\wrapper.js:170:5)
    at ChildProcess.emit (events.js:321:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)`

**Comment by manuRichard** [comment]
Closing this, sorry. The missing comma is not causing the issue I'm having.
