### ISSUE TITLE
CPU overload due to wrapper infinitely launching new Node processes when an unhandled error occurs

### ISSUE THREAD

**Issue by jkomoda** [coreybutler/node-windows#375]
**Issue:**

When running port scans on nodejs apps running via node-windows, the server CPU and memory is being overloaded to 100% due to node-windows continuously launching new processes when receiving the error:
```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at TCP.onread (net.js:615:25)
```

The scanner client connects to server, sends TCP packet data, then disconnects.  Each time the disconnect happens, the wrapper catches this error and launches a new process here:
https://github.com/coreybutler/node-windows/blob/27779d9caafe9854fa5767574ac288d98447c0ff/lib/wrapper.js#L205

**How To Reproduce:**
1. Locally, use node-windows to install a node application that runs a simple http server listening on a specific port
2. Install Nessus Expert trial version locally and run a scan that targets the application port
3. Observe in task manager that multiple processes are being created from the wrapper each time the scanner TCP client disconnects

**Expected Behavior:**
The wrapper to handle the `ECONNRESET` error gracefully and not launch more processes without killing the previous one

**Screenshots:**
1. Create the node server and run as node-windows service

![Screenshot 2024-04-25 184934](https://github.com/coreybutler/node-windows/assets/98358547/03560a1d-cdb9-40a3-bc0c-49ba0196c617)

2. Run the Nessus scans targeting the port and observe the daemon logs showing the TCP clients connecting, sending data, then disconnecting

![Screenshot 2024-04-25 183303](https://github.com/coreybutler/node-windows/assets/98358547/3d4c5b40-6074-45a1-bfa5-c9636b1b51b7)

![Screenshot 2024-04-25 183342](https://github.com/coreybutler/node-windows/assets/98358547/1a091162-13e2-4d7c-93e7-3c282139d6ff)

3. In Event Viewer, observe the `read ECONNRESET` error being logged from `wrapper.js`

![Screenshot 2024-04-25 183526](https://github.com/coreybutler/node-windows/assets/98358547/c42953f6-a993-46e3-a1e8-bb32f688bbfe)

4. Observe Node processes continuously being launched over and over

![Screenshot 2024-04-25 183955](https://github.com/coreybutler/node-windows/assets/98358547/c345384a-70a5-493c-9002-9184693ba630)

**Comment by jkomoda** [comment]
@coreybutler is there a way to handle these types of errors properly? For the sake of our port scan tests, I've added this snippet for a work-around
![Screenshot 2024-04-25 184806](https://github.com/coreybutler/node-windows/assets/98358547/443eedac-24ba-4a77-ae74-5414396ff4a0)

**Comment by coreybutler** [comment]
@jkomoda something seems off here. The wrapper won't relaunch the child process unless it exits. Even when it does, there is exponential backoff. This looks suspiciously like the server is being closed when the client disconnects or when an error occurs, but the process isn't exiting when the server closes (which it should). That would be part of the application code.

I'm not entirely clear on the environment this is operating in, but I'd try running without node-windows to compare. Ultimately, it seems like the errors should be handled in the app though. The uncaughtException is just a failsafe.

**Comment by jkomoda** [comment]
@coreybutler thanks for the reply.  One important thing I left out was that the process runs fine in the console (non node-windows).  It doesn't crash we don't seem to be getting any `ECONNRESET` errors

![Screenshot 2024-04-30 091114](https://github.com/coreybutler/node-windows/assets/98358547/32a2c153-b4e0-4c4c-beb8-c032be2c9f51)

**Comment by jkomoda** [comment]
I have tested the code changes in the PR and it now seems to be working fine.  So basically we are leaking the 'ghost' servers and aren't closing the previous one before creating another one correct?

**Comment by coreybutler** [comment]
Honest truth, I completely forgot about that PR. My comments still stand... I don't want to flood the logs unnecessarily. Aside from that, I'm fine with merging that PR. If you want to apply the updates to that PR, I should be able to include them and cut a new release.

Yes, I believe you are correct re: ghost servers.

**Comment by jkomoda** [comment]
@coreybutler awesome! I've created a PR which adds an option to ignore warning logs when creating the daemon service - [Add daemon option to suppress warning logs #376](https://github.com/coreybutler/node-windows/pull/376)

I wanted to add it to the existing PR - [Prevent security scanner from killing wrapper with ECONNRESET #277](https://github.com/coreybutler/node-windows/pull/277) but I have no access to push to his branch, and not sure if/when he will be active.

If you can merge both of these PRs, and create a new release that would much appreciated! Thanks!

**Comment by jkomoda** [comment]
@coreybutler just checking up, is it possible to merge these PRs and cut the new release?

**Comment by jkomoda** [comment]
@coreybutler any updates on this?

**Comment by radcapitalist** [comment]
@coreybutler Did anything ever happen with @jkomoda's PRs? We appear to be hitting this same issue, reported as [issue #389](https://github.com/coreybutler/node-windows/issues/389).

**Comment by radcapitalist** [comment]
Turns out our customer was also using Tenable Nessus for port scanning. Turning that off solved their problem. They will add exclusions to prevent our ports from being scanned.
Many thanks to @jkomoda for posting this - it helped us solve our customer's problem more quickly than would have been the case without this documented issue.
I will dup issue #389 to this.

**Comment by Tiuipuv** [comment]
We also encountered this issue, and resolved via 3 levels of defense:
 * First, I replaced the silent server with just a heartbeat. This guarantees the wrapper stays alive permanently, while also not spinning up an unused server. This protects the wrapper process from the various security scanners that can cause the exception in the first place.
 * Second, The process Uncaught Exception handler did not properly exit the app, causing the app to be in an undefined state. 90% of the time this is fine, the other 10% can lead to nodejs high CPU, zombie processes, and other undefined app behavior. This is fixed with a process.exit(1) after logging. See: https://nodejs.org/api/process.html#warning-using-uncaughtexception-correctly
 * Lastly, in the (now very unlikely) event of an uncaughtException, since the wrapper process now exits, there is a new installer option to have windows detect that exit and respawn the wrapper process, called `autoServiceRestart`.

These changes are live on our fork [here](https://github.com/Evernorth/node-windows/tree/feat-auto_service_restart), with an open PR #391. Hope to see it merged!
