### ISSUE TITLE
no way to specify service logon info

### ISSUE THREAD

**Issue by arthurblake** [coreybutler/node-windows#39]
Thanks for this elegant module. One thing that threw me while reading the doc is the user attribute. I assumed it was transferred over to the service logon information on the installed service, but it's not. Instead it's just the user account used to run the service setup command.

That being said, having the ability to programattically specify the service logon credentials is something I really need. Why not create another set of credentials in the config for that? It looks like it would be a quite simple modification, given that winsw supports this (under the serviceaccount xml attribute.)

One potential security issue is that the user account and password are placed in clear text in the xml file, so if this is done perhaps there would be a post install hook that munges the password in xml?

(P.S. Also, this is minor, but would be great if generateXml created xml that was formatted nicely for readability.)

**Comment by vsspt** [comment]
I'm having the following error when using the /p feature:
`C:\Program Files\WinSW>winsw.exe install /p
2017-07-19 14:34:40,896 INFO  - Starting ServiceWrapper in the CLI mode
Username: admin
Password: **********
Set Account rights to allow log on as a service (y/n)?: y
2017-07-19 14:34:49,567 FATAL - WMI Operation failure: StatusInvalidServiceAccount
WMI.WmiException: StatusInvalidServiceAccount
   at WMI.WmiRoot.BaseHandler.CheckError(ManagementBaseObject result)
   at WMI.WmiRoot.ClassHandler.Invoke(Object proxy, MethodInfo method, Object[] args)
   at WMI.Win32ServicesProxy.Create(String , String , String , ServiceType , ErrorControl , StartMode , Boolean , String , String , String[]
 )
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   at winsw.WrapperService.Main(String[] args)
WMI.WmiException: StatusInvalidServiceAccount
   at WMI.WmiRoot.BaseHandler.CheckError(ManagementBaseObject result)
   at WMI.WmiRoot.ClassHandler.Invoke(Object proxy, MethodInfo method, Object[] args)
   at WMI.Win32ServicesProxy.Create(String , String , String , ServiceType , ErrorControl , StartMode , Boolean , String , String , String[]
 )
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   at winsw.WrapperService.Main(String[] args)

C:\Program Files\WinSW>`

I'm using the WinSW 2.1.0.0 version.
